package com.example.gcalc.fancyMath;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Screen;
import javafx.stage.Stage;

public class fancyMathTest extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) {
        Group g = new Group();
        WebView wv = new WebView();
        WebEngine we = wv.getEngine();
        String mathMLContent =
                """
                        <?xml version="1.0"?>
                        <!DOCTYPE math PUBLIC "-//W3C//DTD MathML 2.0//EN" "http://www.w3.org/TR/MathML2/dtd/mathml2.dtd">
                        <math>
                          <mtable>
                            <mtr>
                              <mtd>
                                <mrow>
                                  <mrow>
                                    <mrow>
                                      <mrow>
                                        <mi>a</mi>
                                        <mo>&#x2062;<!-- INVISIBLE TIMES --></mo>
                                        <msup>
                                          <mi>x</mi>
                                          <mn>2</mn>
                                        </msup>
                                      </mrow>
                                      <mo>+</mo>
                                      <mi>b</mi>
                                      <mo>&#x2062;<!-- INVISIBLE TIMES --></mo>
                                      <mi>x</mi>
                                    </mrow>
                                    <mo>+</mo>
                                    <mi>c</mi>
                                  </mrow>
                                </mrow>
                              </mtd>
                              <mtd>
                                <mo>=</mo>
                              </mtd>
                              <mtd>
                                <mn>0</mn>
                              </mtd>
                            </mtr>
                            <mtr>
                              <mtd>
                                <mrow>
                                  <mrow>
                                    <mi>a</mi>
                                    <mo>&#x2062;<!-- INVISIBLE TIMES --></mo>
                                    <msup>
                                      <mi>x</mi>
                                      <mn>2</mn>
                                    </msup>
                                  </mrow>
                                  <mo>+</mo>
                                  <mi>b</mi>
                                  <mo>&#x2062;<!-- INVISIBLE TIMES --></mo>
                                  <mi>x</mi>
                                </mrow>
                              </mtd>
                              <mtd>
                                <mo>=</mo>
                              </mtd>
                              <mtd>
                                <mo>−</mo>
                                <mi>c</mi>
                              </mtd>
                            </mtr>
                            <mtr>
                              <mtd>
                                <mrow>
                                  <mrow>
                                    <msup>
                                      <mi>x</mi>
                                      <mn>2</mn>
                                    </msup>
                                  </mrow>
                                  <mo>+</mo>
                                  <mfrac>
                                    <mi>b</mi>
                                    <mi>a</mi>
                                  </mfrac>
                                  <mo>⁤</mo>
                                  <mi>x</mi>
                                </mrow>
                              </mtd>
                              <mtd>
                                <mo>=</mo>
                              </mtd>
                              <mtd>
                                <mfrac>
                                  <mrow>
                                    <mo>−</mo>
                                    <mi>c</mi>
                                  </mrow>
                                  <mi>a</mi>
                                </mfrac>
                              </mtd>
                              <mtd>
                                <mrow>
                                  <mtext style="color: red; font-size: 10pt;">Divide out leading coefficient.</mtext>
                                </mrow>
                              </mtd>
                            </mtr>
                            <mtr>
                              <mtd>
                                <mrow>
                                  <mrow>
                                    <mrow>
                                      <msup>
                                        <mi>x</mi>
                                        <mn>2</mn>
                                      </msup>
                                    </mrow>
                                    <mo>+</mo>
                                    <mfrac>
                                      <mrow>
                                        <mi>b</mi>
                                      </mrow>
                                      <mi>a</mi>
                                    </mfrac>
                                    <mo>⁤</mo>
                                    <mi>x</mi>
                                    <mo>+</mo>
                                    <msup>
                                      <mrow>
                                        <mo>(</mo>
                                        <mfrac>
                                          <mrow>
                                            <mi>b</mi>
                                          </mrow>
                                          <mrow>
                                            <mn>2</mn>
                                            <mi>a</mi>
                                          </mrow>
                                        </mfrac>
                                        <mo>)</mo>
                                      </mrow>
                                      <mn>2</mn>
                                    </msup>
                                  </mrow>
                                </mrow>
                              </mtd>
                              <mtd>
                                <mo>=</mo>
                              </mtd>
                              <mtd>
                                <mrow>
                                  <mfrac>
                                    <mrow>
                                      <mo>−</mo>
                                      <mi>c</mi>
                                      <mo>(</mo>
                                      <mn>4</mn>
                                      <mi>a</mi>
                                      <mo>)</mo>
                                    </mrow>
                                    <mrow>
                                      <mi>a</mi>
                                      <mo>(</mo>
                                      <mn>4</mn>
                                      <mi>a</mi>
                                      <mo>)</mo>
                                    </mrow>
                                  </mfrac>
                                  <mo>+</mo>
                                  <mfrac>
                                    <mrow>
                                      <msup>
                                        <mi>b</mi>
                                        <mn>2</mn>
                                      </msup>
                                    </mrow>
                                    <mrow>
                                      <mn>4</mn>
                                      <msup>
                                        <mi>a</mi>
                                        <mn>2</mn>
                                      </msup>
                                    </mrow>
                                  </mfrac>
                                </mrow>
                              </mtd>
                              <mtd>
                                <mrow>
                                  <mtext style="color: red; font-size: 10pt;">Complete the square.</mtext>
                                </mrow>
                              </mtd>
                            </mtr>
                            <mtr>
                              <mtd>
                                <mrow>
                                  <mrow>
                                    <mo>(</mo>
                                    <mi>x</mi>
                                    <mo>+</mo>
                                    <mfrac>
                                      <mrow>
                                        <mi>b</mi>
                                      </mrow>
                                      <mrow>
                                        <mn>2</mn>
                                        <mi>a</mi>
                                      </mrow>
                                    </mfrac>
                                    <mo>)</mo>
                                    <mo>(</mo>
                                    <mi>x</mi>
                                    <mo>+</mo>
                                    <mfrac>
                                      <mrow>
                                        <mi>b</mi>
                                      </mrow>
                                      <mrow>
                                        <mn>2</mn>
                                        <mi>a</mi>
                                      </mrow>
                                    </mfrac>
                                    <mo>)</mo>
                                  </mrow>
                                </mrow>
                              </mtd>
                              <mtd>
                                <mo>=</mo>
                              </mtd>
                              <mtd>
                                <mfrac>
                                  <mrow>
                                    <msup>
                                      <mi>b</mi>
                                      <mn>2</mn>
                                    </msup>
                                    <mo>−</mo>
                                    <mn>4</mn>
                                    <mi>a</mi>
                                    <mi>c</mi>
                                  </mrow>
                                  <mrow>
                                    <mn>4</mn>
                                    <msup>
                                      <mi>a</mi>
                                      <mn>2</mn>
                                    </msup>
                                  </mrow>
                                </mfrac>
                              </mtd>
                              <mtd>
                                <mrow>
                                  <mtext style="color: red; font-size: 10pt;">Discriminant revealed.</mtext>
                                </mrow>
                              </mtd>
                            </mtr>
                            <mtr>
                              <mtd>
                                <mrow>
                                  <mrow>
                                    <msup>
                                      <mrow>
                                        <mo>(</mo>
                                        <mi>x</mi>
                                        <mo>+</mo>
                                        <mfrac>
                                          <mrow>
                                            <mi>b</mi>
                                          </mrow>
                                          <mrow>
                                            <mn>2</mn>
                                            <mi>a</mi>
                                          </mrow>
                                        </mfrac>
                                        <mo>)</mo>
                                      </mrow>
                                      <mn>2</mn>
                                    </msup>
                                  </mrow>
                                </mrow>
                              </mtd>
                              <mtd>
                                <mo>=</mo>
                              </mtd>
                              <mtd>
                                <mfrac>
                                  <mrow>
                                    <msup>
                                      <mi>b</mi>
                                      <mn>2</mn>
                                    </msup>
                                    <mo>−</mo>
                                    <mn>4</mn>
                                    <mi>a</mi>
                                    <mi>c</mi>
                                  </mrow>
                                  <mrow>
                                    <mn>4</mn>
                                    <msup>
                                      <mi>a</mi>
                                      <mn>2</mn>
                                    </msup>
                                  </mrow>
                                </mfrac>
                              </mtd>
                              <mtd>
                                <mrow>
                                  <mtext style="color: red; font-size: 10pt;"></mtext>
                                </mrow>
                              </mtd>
                            </mtr>
                            <mtr>
                              <mtd>
                                <mrow>
                                  <mrow>
                                    <mrow>
                                      <mi>x</mi>
                                      <mo>+</mo>
                                      <mfrac>
                                        <mrow>
                                          <mi>b</mi>
                                        </mrow>
                                        <mrow>
                                          <mn>2</mn>
                                          <mi>a</mi>
                                        </mrow>
                                      </mfrac>
                                    </mrow>
                                  </mrow>
                                </mrow>
                              </mtd>
                              <mtd>
                                <mo>=</mo>
                              </mtd>
                              <mtd>
                                <msqrt>
                                  <mfrac>
                                    <mrow>
                                      <msup>
                                        <mi>b</mi>
                                        <mn>2</mn>
                                      </msup>
                                      <mo>−</mo>
                                      <mn>4</mn>
                                      <mi>a</mi>
                                      <mi>c</mi>
                                    </mrow>
                                    <mrow>
                                      <mn>4</mn>
                                      <msup>
                                        <mi>a</mi>
                                        <mn>2</mn>
                                      </msup>
                                    </mrow>
                                  </mfrac>
                                </msqrt>
                              </mtd>
                              <mtd>
                                <mrow>
                                  <mtext style="color: red; font-size: 10pt;"></mtext>
                                </mrow>
                              </mtd>
                            </mtr>
                            <mtr>
                              <mtd>
                                <mi>x</mi>
                              </mtd>
                              <mtd>
                                <mo>=</mo>
                              </mtd>
                              <mtd>
                                <mfrac>
                                  <mrow>
                                    <mo>−</mo>
                                    <mi>b</mi>
                                  </mrow>
                                  <mrow>
                                    <mn>2</mn>
                                    <mi>a</mi>
                                  </mrow>
                                </mfrac>
                                <mo>±</mo>
                                <mrow>
                                  <mo>{</mo>
                                  <mi>C</mi>
                                  <mo>}</mo>
                                </mrow>
                                <msqrt>
                                  <mfrac>
                                    <mrow>
                                      <msup>
                                        <mi>b</mi>
                                        <mn>2</mn>
                                      </msup>
                                      <mo>−</mo>
                                      <mn>4</mn>
                                      <mi>a</mi>
                                      <mi>c</mi>
                                    </mrow>
                                    <mrow>
                                      <mn>4</mn>
                                      <msup>
                                        <mi>a</mi>
                                        <mn>2</mn>
                                      </msup>
                                    </mrow>
                                  </mfrac>
                                </msqrt>
                              </mtd>
                              <mtd>
                                <mrow>
                                  <mtext style="color: red; font-size: 10pt;">There's the vertex formula.</mtext>
                                </mrow>
                              </mtd>
                            </mtr>
                            <mtr>
                              <mtd>
                                <mi>x</mi>
                              </mtd>
                              <mtd>
                                <mo>=</mo>
                              </mtd>
                              <mtd>
                                <mfrac>
                                  <mrow>
                                    <mo>−</mo>
                                    <mi>b</mi>
                                    <mo>±</mo>
                                    <mrow>
                                      <mo>{</mo>
                                      <mi>C</mi>
                                      <mo>}</mo>
                                    </mrow>
                                    <msqrt>
                                      <msup>
                                        <mi>b</mi>
                                        <mn>2</mn>
                                      </msup>
                                      <mo>−</mo>
                                      <mn>4</mn>
                                      <mi>a</mi>
                                      <mi>c</mi>
                                    </msqrt>
                                  </mrow>
                                  <mrow>
                                    <mn>2</mn>
                                    <mi>a</mi>
                                  </mrow>
                                </mfrac>
                              </mtd>
                              <mtd>
                                <mrow>
                                  <mtext style="color: red; font-size: 10pt;"></mtext>
                                </mrow>
                              </mtd>
                            </mtr>
                          </mtable>
                        </math>""";
        we.loadContent("<!DOCTYPE html><html><body>" + mathMLContent + "</body></html>");
        g.getChildren().add(wv);
        Scene scene = new Scene(g, 750, 300);
        stage.setScene(scene);
        stage.show();
    }
}